//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerManageSystem.EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerInfo
    {
        public string ComputerId { get; set; }
        public string Brand { get; set; }
        public string CPU { get; set; }
        public Nullable<int> Memory { get; set; }
        public Nullable<int> HardDisk { get; set; }
        public string Employee { get; set; }
    }
}
